## 00. pytorch fundamentals

resource notebook - https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


In [ ]:
!nvidia-smi #does not work when using CPU

Sat Sep 30 18:43:20 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## creating tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as oythin in
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
print(vector)
print(f'vector.ndim: {vector.ndim}')
print(f'vector.shape: {vector.shape}')

tensor([7, 7])
vector.ndim: 1
vector.shape: torch.Size([2])


In [ ]:
#matrix
matrix = torch.tensor([[1, 2],
                      [3, 4]])
print(matrix)
print(f'index 1 {matrix[1]}')
print(f'matrix.ndim {matrix.ndim}')
print(f'matrix.shape {matrix.shape}')

tensor([[1, 2],
        [3, 4]])
index 1 tensor([3, 4])
matrix.ndim 2
matrix.shape torch.Size([2, 2])


In [ ]:
# tensor

tensor = torch.tensor([[[7, 8, 9], [4, 5, 6], [1, 2, 3]],
                        [[0, 0, 0], [1, 1, 1], [2, 2, 2]]])

print(tensor)
print(f'tensor.ndim {tensor.ndim}')
print(f'tensor.shape {tensor.shape}')

tensor([[[7, 8, 9],
         [4, 5, 6],
         [1, 2, 3]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]]])
tensor.ndim 3
tensor.shape torch.Size([2, 3, 3])


In [ ]:
tensor[1]

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

### random tensor

In [ ]:
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)
print(f'random_tensor.ndim {random_tensor.ndim} (mumber of dimension)')
print(f'random_tensor.shape {random_tensor.shape}')

tensor([[[8.7972e-02, 1.8602e-01, 6.2097e-01, 4.5644e-01],
         [4.3791e-01, 5.2281e-02, 5.8145e-01, 5.4052e-01],
         [3.3453e-01, 7.8326e-01, 7.1537e-01, 4.9041e-01]],

        [[7.9114e-02, 8.8483e-01, 6.5719e-01, 6.7460e-01],
         [7.3082e-03, 1.0322e-01, 2.0473e-01, 6.1931e-01],
         [3.1686e-04, 5.1584e-01, 7.0332e-01, 2.7842e-01]]])
random_tensor.ndim 3 (mumber of dimension)
random_tensor.shape torch.Size([2, 3, 4])


In [ ]:
# creating a RGB (3 chanels) image with h & w = 244
random_image_size_tensor = torch.rand(size= (224, 224, 3))
# print(random_image_size_tensor) #too messy
print(f'random_image_size_tensor.ndim {random_image_size_tensor.ndim} (mumber of dimension)')
print(f'random_image_size_tensor.shape {random_image_size_tensor.shape}')

random_image_size_tensor.ndim 3 (mumber of dimension)
random_image_size_tensor.shape torch.Size([224, 224, 3])


## 0s & 1s

In [ ]:
# all zeros
zeros = torch.zeros(3, 4)
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# all ones
ones = torch.ones(3, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
# eye (extra)
eye = torch.eye(5, 5)
print(eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


## creating range of tensors and tensors-like

In [ ]:
# using torch.range()
# range is old... go for arange
one_to_ten = torch.arange(0, 11, step= 1)
print(one_to_ten)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [ ]:
# creating tensors liek
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)
print(f'ten_zeros.dtype {ten_zeros.dtype}')

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
ten_zeros.dtype torch.int64


In [ ]:
# alt, but notice the type....
ten_zeros = torch.zeros(size = one_to_ten.shape)
print(f'ten_zeros.dtype {ten_zeros.dtype}')

ten_zeros.dtype torch.float32


In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0, 5.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)

print(float_32_tensor)
print(f'float_32_tensor.dtype: {float_32_tensor.dtype}')

tensor([1., 2., 3., 5.])
float_32_tensor.dtype: torch.float32


In [ ]:
#float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)
print(f'float_16_tensor.dtype: {float_16_tensor.dtype}')

tensor([1., 2., 3., 5.], dtype=torch.float16)
float_16_tensor.dtype: torch.float16


In [ ]:
mix_tensor = float_16_tensor * float_32_tensor
print(mix_tensor)
print(f'mix_tensor.dtype: {mix_tensor.dtype}')

tensor([ 1.,  4.,  9., 25.])
mix_tensor.dtype: torch.float32


In [ ]:
int_32_tensor = torch.tensor([1, 3, 5, 7], dtype=torch.int32)
int_float_tensor = mix_tensor * int_32_tensor
print(int_float_tensor)
print(f'int_float_tensor.dtype:  {int_float_tensor.dtype}')

tensor([  1.,  12.,  45., 175.])
int_float_tensor.dtype:  torch.float32


## getting info from tensors
- tensors not right datatype (to do get datatype from a tensor, use `tensor.dtype`)
- tensors not right shape (to get shape from a tensor use `tensor.shape`)
- tensors not on the right device (to get device from tensor use `tensor.device`)

In [ ]:
# create a tensor (basicaly what I was doing before)
#but doing some different things
some_tensor = torch.rand(size=(3, 4), dtype=torch.float16, device = 'cuda')
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'shape of tensor: {some_tensor.shape}')
print(f'device tensor is on: {some_tensor.device}')

#sending tensor to cpu
some_tensor = some_tensor.to('cpu')
print(f'device tensor is on: {some_tensor.device}')

tensor([[0.0305, 0.2386, 0.2252, 0.0679],
        [0.2581, 0.7803, 0.2920, 0.8999],
        [0.8926, 0.6328, 0.2188, 0.8057]], device='cuda:0',
       dtype=torch.float16)
Datatype of tensor: torch.float16
shape of tensor: torch.Size([3, 4])
device tensor is on: cuda:0
device tensor is on: cpu


 ### manupulating tensor (tensor operations)

 Tensor operating include:
 * add
 * sub
 * mul (element wise)
 * div
 * dot (matrix mul)

In [ ]:
tensor = torch.tensor([1, 2, 3])

# add
print(tensor + 42)

#  mul
print(tensor * 3)

# sub
print(tensor - 4)

tensor([43, 44, 45])
tensor([3, 6, 9])
tensor([-3, -2, -1])


In [ ]:
# pytorch funcs (basic)
print(torch.mul(tensor, 3))
print(torch.add(tensor, 4))

tensor([3, 6, 9])
tensor([5, 6, 7])


In [ ]:
# mul (element wise)
print(torch.matmul(tensor, tensor))

tensor(14)


In [ ]:
# he does completely different on the video, but that's ok
# dot (matrix mul)

tensor_a = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

tensor_b = torch.tensor([[7, 8, 9],
                         [10, 11, 12]])
# result = torch.matmul(tensor_a, tensor_b.T)
result = tensor_a @ tensor_b.T
print(result)

tensor([[ 50,  68],
        [122, 167]])


In [ ]:
#on the video he does something like this

print(torch.matmul(torch.rand(3,2), torch.rand(2, 3)))

#it's fun to see how the dimentions needs to be to work well ;)

tensor([[0.4606, 0.3820, 1.0313],
        [0.6817, 0.4403, 1.2580],
        [0.5799, 0.3409, 0.9981]])


## min, max, mean, sum, etc...

In [ ]:
x = torch.arange(0, 100, 10)
print(x)
print(f'min: {x.min()}')
print(f'max: {x.max()}')
# torch.mean requires tensor to be float32
print(f'mean: {x.type(torch.float32).mean()}')
print(f'sum: {x.sum()}')

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
min: 0
max: 90
mean: 45.0
sum: 450


In [ ]:
# argmin, argmax
print(f'argmin: {x.argmin()}')
print(f'argmax: {x.argmax()}')

argmin: 0
argmax: 9


In [ ]:
## reshaping, stacking, (un)squeezing
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# chaging z changes x
# a view of a tensor shares the same memory as the original one
z = x_reshaped.view(9, 1)
print(f'z: {z}')
print(f'z.shape: {z.shape}')
z[3, 0] = 999
print(x_reshaped)
print(z)

z: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
z.shape: torch.Size([9, 1])
tensor([[  1.,   2.,   3.],
        [999.,   5.,   6.],
        [  7.,   8.,   9.]])
tensor([[  1.],
        [  2.],
        [  3.],
        [999.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.]])


In [ ]:
# stacking tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
print(x_stacked)
x_stacked = torch.stack([x, x, x, x], dim=0)
print('\n', x_stacked)

tensor([[  1.,   1.,   1.,   1.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [999., 999., 999., 999.],
        [  5.,   5.,   5.,   5.],
        [  6.,   6.,   6.,   6.],
        [  7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.]])

 tensor([[  1.,   2.,   3., 999.,   5.,   6.,   7.,   8.,   9.],
        [  1.,   2.,   3., 999.,   5.,   6.,   7.,   8.,   9.],
        [  1.,   2.,   3., 999.,   5.,   6.,   7.,   8.,   9.],
        [  1.,   2.,   3., 999.,   5.,   6.,   7.,   8.,   9.]])


In [ ]:
# (un)squeeze
y = torch.arange(1., 10.)
print(y, y.shape)
print('\n')
y_squeezed = y.squeeze()
print(y_squeezed, y_squeezed.size())
# ???

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])


In [ ]:
# adding extra dim to the one that was supposed to have
y_unsqueezed = y.unsqueeze(dim=1)
print(y_unsqueezed, y_unsqueezed.size())

y_squeezed = y_unsqueezed.squeeze()
print('\n', y_squeezed, y_squeezed.size())

y_permuted = y_unsqueezed.permute(1, 0)
print('\n', y_permuted, y_permuted.size())

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]]) torch.Size([9, 1])

 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]) torch.Size([9])

 tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


In [ ]:
# permute RGB image example
rgb = torch.rand(size=(224, 224, 3))
print(rgb.shape)
rgb[128, 223, 1] = 666
rgb_permuted = rgb.permute(1, 2, 0)
print(rgb_permuted.shape)
print(f'added value to new shape: ', rgb_permuted[223, 1, 128])

rgb_permuted[45, 0, 37] = 777
print(f'the value on the original tensor but changed on the new on: {rgb[37, 45, 0]}')
# this is to proof that permute is a view, i.e the new tensor shares the memory of the original one

torch.Size([224, 224, 3])
torch.Size([224, 3, 224])
added value to new shape:  tensor(666.)
the value on the original tensor but changed on the new on: 777.0


## indexing

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## pytorch tensor and numpy

In [ ]:
# numpy array to tensor
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
print(f'numpy array: {array}')
print(f'torch tensor: {tensor}')

numpy array: [1. 2. 3. 4. 5. 6. 7.]
torch tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [ ]:
# change the value of the array
array = array + 2
print(f'numpy array: {array}')
print(f'torch tensor: {tensor}')

numpy array: [3. 4. 5. 6. 7. 8. 9.]
torch tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [ ]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reptoducbility

In [ ]:
# seeding random so it's controlled ;)

RANDOM_SEED = 1337

torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a, '\n')
print(random_tensor_b, '\n')
print(random_tensor_a == random_tensor_b)

tensor([[0.0783, 0.4956, 0.6231, 0.4224],
        [0.2004, 0.0287, 0.5851, 0.6967],
        [0.1761, 0.2595, 0.7086, 0.5809]]) 

tensor([[0.0783, 0.4956, 0.6231, 0.4224],
        [0.2004, 0.0287, 0.5851, 0.6967],
        [0.1761, 0.2595, 0.7086, 0.5809]]) 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPU!!!

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.device('cuda')

device(type='cuda')

In [ ]:
# setup device agnostic code

device = 'cuda' if torch.cuda.is_available else 'cpu'

In [ ]:
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
# putting tensor & model to the GPU

# default is on cpu

tensor = torch.arange(1, 10)
print(tensor.device)

cpu


In [ ]:
tensor = tensor.to(device)
print(tensor.device)

cuda:0


In [ ]:
# back to cpu
tensor = tensor.to('cpu')
print(tensor.device)
numpy_array = tensor.numpy()
print(numpy_array)

cpu
[1 2 3 4 5 6 7 8 9]
